/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __IPQ9650_H__
#define __IPQ9650_H__

#define TCSR_BOOT_MISC_REG			((u32 *)0x195C100)
#define PSHOLD_CTL_BASE				0x004AB000

#define ROOT_FS_PART_NAME			"rootfs"
#define ROOT_FS_ATL_PART_NAME			"rootfs_1"

#define TME_OEM_ATE_FUSE_START			0x000A40E8
#define TME_OEM_ATE_FUSE_CNT			0x1
#define TME_OEM_ATE_FUSE_READ_SIZE		0x8

#define TME_OEM_MRC_HASH_FUSE_START		0x000A4100
#define TME_OEM_MRC_HASH_FUSE_CNT		0x7
#define TME_OEM_MRC_HASH_FUSE_READ_SIZE		0x8

#define TME_AUTH_EN_MASK			0x82
#define TME_OEM_ID_MSK				0xFFFF0000
#define TME_PRODUCT_ID_MSK			0x0000FFFF

#define QFPROM_CORR_TME_OEM_ATE_ROW0_LSB	0xA40E8
#define QFPROM_CORR_TME_OEM_ATE_ROW1_LSB	0xA40F0

#define ROOTFS_AUTH_FUSE			0xA4060
#define OEM_SEC_BOOT_ENABLE			BIT(7)

#ifdef CONFIG_BOOT_BANK_FIXUP
#define BOOTED_BANK_ADDR_IMEM			0x86000D0
#endif

#ifdef CONFIG_FAILSAFE_V2
#define IMEM_ADDR_BOOTCNT			0x86000C8

#define BOOT_FROM_SET_ACTIVE			0
#define BOOT_FROM_SET_INACTIVE			1

#ifdef CONFIG_BOOT_BANK_SMEM_READ
#define BOOT_MODE_NORMAL			0
#define BOOT_MODE_SPL_INACTIVE			1
#define BOOT_MODE_FORCE_INACTIVE		2
#endif

#endif

#define KERNEL_START_ADDR			CFG_SYS_SDRAM_BASE
#define BOOT_PARAMS_ADDR			(KERNEL_START_ADDR + 0x100)
#define FDT_HIGH				0x88500000

/*
 * TCSR Registers
 */
#define TCSR_TZ_WONCE0				0x195C000
#define TCSR_TZ_WONCE1				0x195C004

#define ENABLE_EDL_MODE				BIT(0)

#define EDL_RECOVERY_MODE			0x2
#define UBOOT_RECOVERY_MODE			0x1

#if defined(CONFIG_SPL)
/* Macro to set TCSR register for EDL mode */
#define IPQ_SPL_SET_TCSR_EDL() \
	writel(readl(TCSR_BOOT_MISC_REG) | ENABLE_EDL_MODE, \
	       TCSR_BOOT_MISC_REG)

#define IPQ_SPL_FEATURE_CONFIG2_REG_ADDR	0xA600C
#define IPQ_SPL_TMEL_BYPASS_DISABLE_MASK	BIT(0)

#define IPQ_SPL_FUSE_BOOT_CFG_ADDR		0xA602C
#define IPQ_SPL_FUSE_JTAG_ID_ADDR		0xA607C
#define IPQ_SPL_FUSE_OEM_ID_ADDR		0xA6080
#define IPQ_SPL_FUSE_TME_L_LCS_ADDR		0xA6094
#define IPQ_SPL_FUSE_SERIAL_NUM_ADDR		0xA60A8
#define IPQ_SPL_FUSE_PRODUCT_ID_ADDR		0xA60AC
#define IPQ_SPL_GCC_RESET_DEBUG_ADDR		0x1840000
#define IPQ_SPL_GCC_FSM_CTRL_ADDR		0x1840004
#define IPQ_SPL_GCC_RESET_STATUS_ADDR		0x1841000
#define IPQ_SPL_GCC_FSM_STATUS_ADDR		0x1841004
#define IPQ_SPL_DDR_GPR0_ADDR			0x42D0000

#define IPQ_SPL_FUSE_OEM_TME_ROW_0_ADDR		0xA40E8
#define IPQ_SPL_FUSE_FEATURE_CONFIG_ROW_0_ADDR	0xA4018
#define IPQ_SPL_FUSE_FEATURE_CONFIG_ROW_1_ADDR	0xA4020
#define IPQ_SPL_FUSE_OEM_CONFIG_ROW_0_ADDR	0xA4060
#define IPQ_SPL_FUSE_OEM_CONFIG_ROW_1_ADDR	0xA4068

/*
 * SOC LCS
 */
#define IPQ_SPL_SOC_LCS_MASK			0x0000001E
#define IPQ_SPL_SOC_LCS_SHFT			0x1

/*
 * Feature Provisioning
 */
#define IPQ_SPL_FEAT_PROV_OUT0_ADDR		0x000A20A0
#define IPQ_SPL_FEAT_PROV_OUT2_ADDR		0x000A20A8
#define IPQ_SPL_FEAT_PROV_TMEL_MASK		0x3
#define IPQ_SPL_FEAT_PROV_APSS_MASK		0x1E00
#define IPQ_SPL_FEAT_PROV_Q6_MASK		0x100000
#define IPQ_SPL_FEAT_PROV_APSS_SHIFT		0x9
#define IPQ_SPL_FEAT_PROV_Q6_SHIFT		0x14

/*
 * OTP Version Register
 */
#define IPQ_SPL_QFPROM_PTE_ROW2_LSB_ADDR	0xA4010
#define IPQ_SPL_OTP_TAG_VERSION_MASK		0x07000000
#define IPQ_SPL_OTP_TAG_VERSION_SHIFT		0x18
#define IPQ_SPL_OTP_FM_VERSION_MASK		0x00E00000
#define IPQ_SPL_OTP_FM_VERSION_SHIFT		0x15

/*
 * FEATURE ID Register (QFPROM_CORR_PTE_ROW0_LSB)
 */
#define IPQ_SPL_FUSE_FEATURE_ID_ADDR		0xA4000
#define IPQ_SPL_FEATURE_ID_MASK			0xFF00000
#define IPQ_SPL_FEATURE_ID_SHIFT		0x14

#define IPQ_SPL_DPR_SEC_AUTH_SWID		0x200
#define IPQ_SPL_QCCONFIG_SEC_AUTH_SWID		0x25
#define IPQ_SPL_QCLIB_DDR_SEC_AUTH_SWID		0x41
#define IPQ_SPL_TZ_TEE_SEC_AUTH_SWID		0x1E
#define IPQ_SPL_OP_TEE_SEC_AUTH_SWID		0xCC
#define IPQ_SPL_APPSBL_SEC_AUTH_SWID		0x9

#endif

/* Crashdump minimal configs */
#define CFG_CPU_CONTEXT_DUMP_SIZE		0x180F0
#define TME_CTXT_SIZE				(128 * 1024)
#define CPU_CNTXT_HDR_SIZE			4624

#define CFG_QTI_KERN_WDT_ADDR			*((unsigned int *)0x8600658)
#define CFG_QTI_KERN_TLV_ADDR			*((unsigned int *)0x8600758)

#define WDT2_BASE_ADDR			0xF411000

/* Watchdog Register Offsets */
#define WDT_SECURE			0x000
#define WDT_RST				0x004
#define WDT_EN				0x008
#define WDT_STS				0x00C
#define WDT_BARK_TIME			0x010
#define WDT_BITE_TIME			0x014

/* Bit definitions */
#define WDT_ENABLE_BIT			BIT(0)
#define WDT_RESET_BIT			BIT(0)

/* Sleep clock frequency */
#define WDT_SLEEP_CLK_HZ		32768

/* Default timeout */
#define WDT_DEFAULT_TIMEOUT_MS		31999

#if defined(CONFIG_IPQ_MINIDUMP_VERSION_V2)
#define TLV_BUF_OFFSET				0
#define CFG_TLV_DUMP_SIZE			(23 * 1024)
#else
#define TLV_BUF_OFFSET				0
#define CFG_TLV_DUMP_SIZE			(12 * 1024)
#endif /* CONFIG_IPQ_MINIDUMP_VERSION_V2 */

struct fuse_payload {
	u32 fuse_addr;
	u32 lsb_val;
	u32 msb_val;
};

#if defined(CONFIG_SPL)
#define IPQ_SPL_DEVICE_REG_BASE		0x000020000UL
#define IPQ_SPL_DEVICE_REG_SIZE		0x0085E0000UL

#define IPQ_SPL_OCIMEM_REG_BASE		0x008600000UL
#define IPQ_SPL_OCIMEM_REG_SIZE		0x000020000UL

#define IPQ_SPL_USB_PRIM_REG_BASE	0x008A00000UL
#define IPQ_SPL_USB_PRIM_REG_SIZE	0x000200000UL

#define IPQ_SPL_BOOTIMEM_REG_BASE	0x008C00000UL
#define IPQ_SPL_BOOTIMEM_REG_SIZE	0x000100000UL

#define IPQ_SPL_DEVICE_REG2_BASE	0x00F000000UL
#define IPQ_SPL_DEVICE_REG2_SIZE	0x000E00000UL

#define IPQ_SPL_TMEL_MBOX_REG_BASE	0x022090000UL
#define IPQ_SPL_TMEL_MBOX_REG_SIZE	0x000004000UL

#define IPQ_SPL_DDR_MEM_BASE		0x080000000UL
#define IPQ_SPL_DDR_MEM_SIZE		0x080000000UL

#define IPQ_SPL_TFA_TEXT_BASE		0x08A600000UL
#define IPQ_SPL_TFA_TEXT_SIZE		SZ_512K

#define IPQ_SPL_QCLIB_TEXT_BASE		0x008C7B000UL
#define IPQ_SPL_QCLIB_TEXT_SIZE		0x000074000UL

#define IPQ_SPL_QCLIB_DSF_TEXT_BASE	0x00860F000UL
#define IPQ_SPL_QCLIB_DSF_TEXT_SIZE	0x000010000UL

#define IPQ_SPL_TFA_PRNG_DATA_SIZE		64
#define IPQ_SPL_TFA_PRNG_DATA_DEST_ADDR		0x8600900

#ifdef CONFIG_SPL_DDR2_MEM_BASE
#define IPQ_SPL_DDR2_MEM_BASE          0x800000000UL
#define IPQ_SPL_DDR2_MEM_SIZE          0x380000000UL
#endif

#endif /* CONFIG_SPL */

#ifdef CONFIG_IPQ_SOFTSKU_SUPPORT
/*
 * IPQ_HW_FEATURES - SoftSKU HW feature IDs enforced on IPQ9650.
 * Only list the features actually supported by this SoC.
 * Consumed by arch/arm/mach-ipq/ipq_license.c to build the features[] array.
 */
#define IPQ_HW_FEATURES \
	{SOFTSKU_USB3_INTERFACE_FEATURE_ID,          false}, \
	{SOFTSKU_APPS_CPU_FREQUENCY_FEATURE_ID,      false}, \
	{SOFTSKU_AUDIO_INTERFACE_FEATURE_ID,         false}, \
	{SOFTSKU_NSS_CRYPTO_ENGINE_FEATURE_ID,       false}, \
	{SOFTSKU_PCIE_RC0_FEATURE_ID,                false}, \
	{SOFTSKU_PCIE_RC1_FEATURE_ID,                false}, \
	{SOFTSKU_PCIE_RC2_FEATURE_ID,                false}, \
	{SOFTSKU_PCIE_RC3_FEATURE_ID,                false}, \
	{SOFTSKU_UNIPHY0_FEATURE_ID,                 false}, \
	{SOFTSKU_APSS_PERF_CPU_FREQ_FEATURE_ID,      false}, \
	{SOFTSKU_NSP_FEATURE_ID,                     false}, \
	{SOFTSKU_PCIE_RC4_FEATURE_ID,                false}, \
	{SOFTSKU_PRIME_SUBSYSTEM_FEATURE_ID,         false}, \
	{SOFTSKU_UNIPHY1_SPEED_CONFIG_FEATURE_ID,    false}, \
	{SOFTSKU_UNIPHY2_SPEED_CONFIG_FEATURE_ID,    false},
#endif /* CONFIG_IPQ_SOFTSKU_SUPPORT */

#endif /* __IPQ9650_H__ */
