/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (c) 2018,2020 The Linux Foundation. All rights reserved.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DT_BINDINGS_RESET_IPQ_GCC_IPQ9650_H
#define _DT_BINDINGS_RESET_IPQ_GCC_IPQ9650_H

#define GCC_SDCC_BCR				0
#define GCC_USB0_PHY_BCR			1
#define GCC_USB3PHY_0_PHY_BCR			2
#define GCC_QUSB2_0_PHY_BCR			3
#define GCC_QUSB2_1_PHY_BCR			4
#define GCC_USB_BCR				5
#define GCC_USB1_BCR				6

#define GCC_PCIE0_PHY_BCR			7
#define GCC_PCIE0PHY_PHY_BCR			8
#define GCC_PCIE0_PIPE_ARES			9
#define GCC_PCIE0_CORE_STICKY_RESET		10
#define GCC_PCIE0_AXI_M_ARES			11
#define GCC_PCIE0_AXI_S_ARES			12
#define GCC_PCIE0_AXI_M_STICKY_RESET		13
#define GCC_PCIE0_AXI_S_STICKY_RESET		14
#define GCC_PCIE0_AHB_ARES			15
#define GCC_PCIE0_AUX_ARES			16

#define GCC_PCIE4_PHY_BCR			17
#define GCC_PCIE4PHY_PHY_BCR			18
#define GCC_PCIE4_PIPE_ARES			19
#define GCC_PCIE4_CORE_STICKY_RESET		20
#define GCC_PCIE4_AXI_M_ARES			21
#define GCC_PCIE4_AXI_S_ARES			22
#define GCC_PCIE4_AXI_M_STICKY_RESET		23
#define GCC_PCIE4_AXI_S_STICKY_RESET		24
#define GCC_PCIE4_AHB_ARES			25
#define GCC_PCIE4_AUX_ARES			26

#define GCC_PCIE3_PHY_BCR			27
#define GCC_PCIE3PHY_PHY_BCR			28
#define GCC_PCIE3_PIPE_ARES			29
#define GCC_PCIE3_CORE_STICKY_RESET		30
#define GCC_PCIE3_AXI_M_ARES			31
#define GCC_PCIE3_AXI_S_ARES			32
#define GCC_PCIE3_AXI_M_STICKY_RESET		33
#define GCC_PCIE3_AXI_S_STICKY_RESET		34
#define GCC_PCIE3_AHB_ARES			35
#define GCC_PCIE3_AUX_ARES			36

#define GCC_PCIE1_PHY_BCR			37
#define GCC_PCIE1PHY_PHY_BCR			38
#define GCC_PCIE1_PIPE_ARES			39
#define GCC_PCIE1_CORE_STICKY_RESET		40
#define GCC_PCIE1_AXI_M_ARES			41
#define GCC_PCIE1_AXI_S_ARES			42
#define GCC_PCIE1_AXI_M_STICKY_RESET		43
#define GCC_PCIE1_AXI_S_STICKY_RESET		44
#define GCC_PCIE1_AHB_ARES			45
#define GCC_PCIE1_AUX_ARES			46

#define GCC_PCIE2_PHY_BCR			47
#define GCC_PCIE2PHY_PHY_BCR			48
#define GCC_PCIE2_PIPE_ARES			49
#define GCC_PCIE2_CORE_STICKY_RESET		50
#define GCC_PCIE2_AXI_M_ARES			51
#define GCC_PCIE2_AXI_S_ARES			52
#define GCC_PCIE2_AXI_M_STICKY_RESET		53
#define GCC_PCIE2_AXI_S_STICKY_RESET		54
#define GCC_PCIE2_AHB_ARES			55
#define GCC_PCIE2_AUX_ARES			56
#define GCC_SDCC_BCR			0
#define GCC_USB0_PHY_BCR		1
#define GCC_USB3PHY_0_PHY_BCR		2
#define GCC_QUSB2_0_PHY_BCR		3
#define GCC_QUSB2_1_PHY_BCR		4
#define GCC_USB_BCR			5
#define GCC_USB1_BCR			6
#define GCC_QPIC_BCR			57

#endif
