/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (c) 2018,2020 The Linux Foundation. All rights reserved.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DT_BINDINGS_RESET_IPQ_GCC_IPQ9650_H
#define _DT_BINDINGS_RESET_IPQ_GCC_IPQ9650_H

#define GCC_SDCC_BCR				0
#define GCC_USB0_PHY_BCR			1
#define GCC_USB3PHY_0_PHY_BCR			2
#define GCC_QUSB2_0_PHY_BCR			3
#define GCC_QUSB2_1_PHY_BCR			4
#define GCC_USB_BCR				5
#define GCC_USB1_BCR				6

#define GCC_PCIE0_PHY_BCR			7
#define GCC_PCIE0PHY_PHY_BCR			8
#define GCC_PCIE0_PIPE_ARES			9
#define GCC_PCIE0_CORE_STICKY_RESET		10
#define GCC_PCIE0_AXI_M_ARES			11
#define GCC_PCIE0_AXI_S_ARES			12
#define GCC_PCIE0_AXI_M_STICKY_RESET		13
#define GCC_PCIE0_AXI_S_STICKY_RESET		14
#define GCC_PCIE0_AHB_ARES			15
#define GCC_PCIE0_AUX_ARES			16

#define GCC_PCIE4_PHY_BCR			17
#define GCC_PCIE4PHY_PHY_BCR			18
#define GCC_PCIE4_PIPE_ARES			19
#define GCC_PCIE4_CORE_STICKY_RESET		20
#define GCC_PCIE4_AXI_M_ARES			21
#define GCC_PCIE4_AXI_S_ARES			22
#define GCC_PCIE4_AXI_M_STICKY_RESET		23
#define GCC_PCIE4_AXI_S_STICKY_RESET		24
#define GCC_PCIE4_AHB_ARES			25
#define GCC_PCIE4_AUX_ARES			26

#define GCC_PCIE3_PHY_BCR			27
#define GCC_PCIE3PHY_PHY_BCR			28
#define GCC_PCIE3_PIPE_ARES			29
#define GCC_PCIE3_CORE_STICKY_RESET		30
#define GCC_PCIE3_AXI_M_ARES			31
#define GCC_PCIE3_AXI_S_ARES			32
#define GCC_PCIE3_AXI_M_STICKY_RESET		33
#define GCC_PCIE3_AXI_S_STICKY_RESET		34
#define GCC_PCIE3_AHB_ARES			35
#define GCC_PCIE3_AUX_ARES			36

#define GCC_PCIE1_PHY_BCR			37
#define GCC_PCIE1PHY_PHY_BCR			38
#define GCC_PCIE1_PIPE_ARES			39
#define GCC_PCIE1_CORE_STICKY_RESET		40
#define GCC_PCIE1_AXI_M_ARES			41
#define GCC_PCIE1_AXI_S_ARES			42
#define GCC_PCIE1_AXI_M_STICKY_RESET		43
#define GCC_PCIE1_AXI_S_STICKY_RESET		44
#define GCC_PCIE1_AHB_ARES			45
#define GCC_PCIE1_AUX_ARES			46

#define GCC_PCIE2_PHY_BCR			47
#define GCC_PCIE2PHY_PHY_BCR			48
#define GCC_PCIE2_PIPE_ARES			49
#define GCC_PCIE2_CORE_STICKY_RESET		50
#define GCC_PCIE2_AXI_M_ARES			51
#define GCC_PCIE2_AXI_S_ARES			52
#define GCC_PCIE2_AXI_M_STICKY_RESET		53
#define GCC_PCIE2_AXI_S_STICKY_RESET		54
#define GCC_PCIE2_AHB_ARES			55
#define GCC_PCIE2_AUX_ARES			56

#define GCC_QPIC_BCR				57
#define GCC_UNIPHY0_SOFT_RESET			58
#define GCC_UNIPHY1_SOFT_RESET			59
#define NSS_CC_UNIPHY_PORT1_TX_RESET		60
#define NSS_CC_UNIPHY_PORT1_RX_RESET		61
#define NSS_CC_UNIPHY_PORT2_TX_RESET		62
#define NSS_CC_UNIPHY_PORT2_RX_RESET		63
#define NSS_CC_UNIPHY_PORT3_TX_RESET		64
#define NSS_CC_UNIPHY_PORT3_RX_RESET		65
#define NSS_CC_PORT1_TX_RESET			66
#define NSS_CC_PORT1_RX_RESET			67
#define NSS_CC_PORT2_TX_RESET			68
#define NSS_CC_PORT2_RX_RESET			69
#define NSS_CC_PORT3_TX_RESET			70
#define NSS_CC_PORT3_RX_RESET			71
#define NSS_CC_PPE_EDMA_RESET			72
#define NSS_CC_PPE_CFG_RESET			73
#define NSS_CC_PORT1_MAC_RESET			74
#define NSS_CC_PORT2_MAC_RESET			75
#define NSS_CC_PORT3_MAC_RESET			76
#define GCC_UNIPHY0_BCR				77
#define GCC_UNIPHY1_BCR				78
#define GCC_UNIPHY2_BCR				79
#define GCC_UNIPHY2_SOFT_RESET			80
#define GCC_UNIPHY0_AHB_RESET			81
#define GCC_UNIPHY1_AHB_RESET			82
#define GCC_UNIPHY2_AHB_RESET			83
#define GCC_UNIPHY0_SYS_RESET			84
#define GCC_UNIPHY1_SYS_RESET			85
#define GCC_UNIPHY2_SYS_RESET			86
#define GCC_UNIPHY0_XPCS_RESET			87
#define GCC_UNIPHY1_XPCS_RESET			88
#define GCC_UNIPHY2_XPCS_RESET			89
#define NSS_CC_PPE_BCR				90
#define NSS_CC_UNIPHY_PORT4_RX_RESET		91
#define NSS_CC_UNIPHY_PORT4_TX_RESET		92
#define NSS_CC_UNIPHY_PORT5_RX_RESET		93
#define NSS_CC_UNIPHY_PORT5_TX_RESET		94
#define NSS_CC_UNIPHY_PORT6_RX_RESET		95
#define NSS_CC_UNIPHY_PORT6_TX_RESET		96
#define NSS_CC_PORT4_RX_RESET			97
#define NSS_CC_PORT4_TX_RESET			98
#define NSS_CC_PORT5_RX_RESET			89
#define NSS_CC_PORT5_TX_RESET			100
#define NSS_CC_PORT6_RX_RESET			101
#define NSS_CC_PORT6_TX_RESET			102
#define NSS_CC_PORT4_MAC_RESET			103
#define NSS_CC_PORT5_MAC_RESET			104
#define NSS_CC_PORT6_MAC_RESET			105
#define GCC_UNIPHY0_AHB_ARES			106
#define GCC_UNIPHY1_AHB_ARES			107
#define GCC_UNIPHY2_AHB_ARES			108
#define GCC_UNIPHY0_SYS_ARES			109
#define GCC_UNIPHY1_SYS_ARES			110
#define GCC_UNIPHY2_SYS_ARES			111
#define GCC_UNIPHY0_XPCS_ARES			112
#define GCC_UNIPHY1_XPCS_ARES			113
#define GCC_UNIPHY2_XPCS_ARES			114
#define NSS_CC_UNIPHY_PORT1_RX_CLK_ARES		115
#define NSS_CC_UNIPHY_PORT1_TX_CLK_ARES		116
#define NSS_CC_UNIPHY_PORT2_RX_CLK_ARES		117
#define NSS_CC_UNIPHY_PORT2_TX_CLK_ARES		118
#define NSS_CC_UNIPHY_PORT3_RX_CLK_ARES		119
#define NSS_CC_UNIPHY_PORT3_TX_CLK_ARES		120
#define NSS_CC_UNIPHY_PORT4_RX_CLK_ARES		121
#define NSS_CC_UNIPHY_PORT4_TX_CLK_ARES		122
#define NSS_CC_UNIPHY_PORT5_RX_CLK_ARES		123
#define NSS_CC_UNIPHY_PORT5_TX_CLK_ARES		124
#define NSS_CC_UNIPHY_PORT6_RX_CLK_ARES		125
#define NSS_CC_UNIPHY_PORT6_TX_CLK_ARES		126
#define NSS_CC_PORT1_RX_CLK_ARES		127
#define NSS_CC_PORT1_TX_CLK_ARES		128
#define NSS_CC_PORT2_RX_CLK_ARES		129
#define NSS_CC_PORT2_TX_CLK_ARES		130
#define NSS_CC_PORT3_RX_CLK_ARES		131
#define NSS_CC_PORT3_TX_CLK_ARES		132
#define NSS_CC_PORT4_RX_CLK_ARES		133
#define NSS_CC_PORT4_TX_CLK_ARES		134
#define NSS_CC_PORT5_RX_CLK_ARES		135
#define NSS_CC_PORT5_TX_CLK_ARES		136
#define NSS_CC_PORT6_RX_CLK_ARES		137
#define NSS_CC_PORT6_TX_CLK_ARES		138
#define NSS_CC_PORT1_MAC_CLK_ARES		139
#define NSS_CC_PORT2_MAC_CLK_ARES		140
#define NSS_CC_PORT3_MAC_CLK_ARES		141
#define NSS_CC_PORT4_MAC_CLK_ARES		142
#define NSS_CC_PORT5_MAC_CLK_ARES		143
#define NSS_CC_PORT6_MAC_CLK_ARES		144
#define GCC_NSS_PARTIAL_RESET			145
#define GCC_NSS_BCR				146
#define NSS_CC_PPE_EDMA_ARES			147
#define GCC_UNIPHY0_PMA_ARES			148
#define GCC_UNIPHY1_PMA_ARES			149
#define GCC_UNIPHY2_PMA_ARES			150
#define GCC_REFGEN_CMN_UPHY_CORE_ARES          151
#define GCC_REFGEN_CMN_UPHY_HCLK_ARES          152

#endif
