// SPDX-License-Identifier: GPL-2.0+
/*
 * Qualcomm IPQ5610 pinctrl
 *
 * Copyright (c) 2019 Sartura Ltd.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * Author: Robert Marko <robert.marko@sartura.hr>
 */

#include <dm.h>

#include "pinctrl-qcom.h"

#define MAX_PIN_NAME_LEN 32
static char pin_name[MAX_PIN_NAME_LEN] __section(".data");

enum ipq5610_functions {
	msm_mux_gpio,
	msm_mux_Led00,
	msm_mux_atest_char_start,
	msm_mux_atest_char_status0,
	msm_mux_atest_char_status1,
	msm_mux_atest_char_status2,
	msm_mux_atest_char_status3,
	msm_mux_atest_tic_en,
	msm_mux_audio_pri0,
	msm_mux_audio_pri1,
	msm_mux_audio_pri2,
	msm_mux_audio_pri3,
	msm_mux_audio_pri_d0,
	msm_mux_audio_pri_d1,
	msm_mux_audio_pri_fsync,
	msm_mux_audio_pri_pclk,
	msm_mux_audio_sec0,
	msm_mux_audio_sec1,
	msm_mux_audio_sec2,
	msm_mux_audio_sec3,
	msm_mux_audio_sec_d0,
	msm_mux_audio_sec_d1,
	msm_mux_audio_sec_fsync,
	msm_mux_audio_sec_pclk,
	msm_mux_bist_complete,
	msm_mux_bist_fail,
	msm_mux_bist_start,
	msm_mux_bist_stop,
	msm_mux_core_voltage_0,
	msm_mux_core_voltage_1,
	msm_mux_core_voltage_2,
	msm_mux_core_voltage_3,
	msm_mux_core_voltage_4,
	msm_mux_core_voltage_5,
	msm_mux_cri_trng0,
	msm_mux_cri_trng1,
	msm_mux_cri_trng2,
	msm_mux_dbg_out_clk,
	msm_mux_ddr_pxi00,
	msm_mux_ddr_pxi01,
	msm_mux_ddr_pxi10,
	msm_mux_ddr_pxi11,
	msm_mux_dg_out,
	msm_mux_gcc_plltest_bypassnl,
	msm_mux_gcc_plltest_resetn,
	msm_mux_gcc_tlmm,
	msm_mux_led01,
	msm_mux_led02,
	msm_mux_led10,
	msm_mux_led11,
	msm_mux_led12,
	msm_mux_led20,
	msm_mux_led21,
	msm_mux_led22,
	msm_mux_mdc_mst,
	msm_mux_mdc_slv0,
	msm_mux_mdc_slv1,
	msm_mux_mdc_slv2,
	msm_mux_mdio_mst,
	msm_mux_mdio_slv,
	msm_mux_mdio_slv0,
	msm_mux_mdio_slv1,
	msm_mux_mdio_slv2,
	msm_mux_mux_tod_out,
	msm_mux_pcie0_clk_req_n,
	msm_mux_pcie0_wake,
	msm_mux_pcie1_clk_req_n,
	msm_mux_pcie1_wake,
	msm_mux_pcie2_clk_req_n,
	msm_mux_pcie2_wake,
	msm_mux_pcie4_phy0,
	msm_mux_pcie4_phy1,
	msm_mux_pll_test,
	msm_mux_pon_active_led,
	msm_mux_pon_mux_sel,
	msm_mux_pon_rx,
	msm_mux_pon_rx_los,
	msm_mux_pon_tx,
	msm_mux_pon_tx_burst,
	msm_mux_pon_tx_dis,
	msm_mux_pon_tx_fault,
	msm_mux_pon_tx_sd,
	msm_mux_pps,
	msm_mux_pwm_out00,
	msm_mux_pwm_out01,
	msm_mux_pwm_out02,
	msm_mux_pwm_out03,
	msm_mux_pwm_out10,
	msm_mux_pwm_out11,
	msm_mux_pwm_out12,
	msm_mux_pwm_out13,
	msm_mux_pwm_out20,
	msm_mux_pwm_out21,
	msm_mux_pwm_out22,
	msm_mux_pwm_out23,
	msm_mux_pwm_out30,
	msm_mux_pwm_out31,
	msm_mux_pwm_out32,
	msm_mux_pwm_out33,
	msm_mux_pwm_out40,
	msm_mux_pwm_out41,
	msm_mux_pwm_out42,
	msm_mux_pwm_out43,
	msm_mux_pwm_out50,
	msm_mux_pwm_out51,
	msm_mux_pwm_out52,
	msm_mux_pwm_out53,
	msm_mux_qdss_cti_trig_in_a0,
	msm_mux_qdss_cti_trig_in_a1,
	msm_mux_qdss_cti_trig_in_b0,
	msm_mux_qdss_cti_trig_in_b1,
	msm_mux_qdss_cti_trig_out_a0,
	msm_mux_qdss_cti_trig_out_a1,
	msm_mux_qdss_cti_trig_out_b0,
	msm_mux_qdss_cti_trig_out_b1,
	msm_mux_qdss_traceclk_a,
	msm_mux_qdss_tracectl_a,
	msm_mux_qdss_tracedata_a,
	msm_mux_qspi_data,
	msm_mux_qspi_clk,
	msm_mux_qspi_cs,
	msm_mux_qup_se0_l0,
	msm_mux_qup_se0_l1,
	msm_mux_qup_se0_l2,
	msm_mux_qup_se0_l3,
	msm_mux_qup_se0_l4,
	msm_mux_qup_se0_l5,
	msm_mux_qup_se1_l0,
	msm_mux_qup_se1_l1,
	msm_mux_qup_se1_l2,
	msm_mux_qup_se1_l3,
	msm_mux_qup_se2_l0,
	msm_mux_qup_se2_l1,
	msm_mux_qup_se2_l2,
	msm_mux_qup_se2_l3,
	msm_mux_qup_se3_l00,
	msm_mux_qup_se3_l01,
	msm_mux_qup_se3_l10,
	msm_mux_qup_se3_l11,
	msm_mux_qup_se3_l2,
	msm_mux_qup_se3_l3,
	msm_mux_qup_se4_l0,
	msm_mux_qup_se4_l1,
	msm_mux_qup_se4_l2,
	msm_mux_qup_se4_l3,
	msm_mux_qup_se4_l4,
	msm_mux_qup_se4_l5,
	msm_mux_qup_se5_l00,
	msm_mux_qup_se5_l01,
	msm_mux_qup_se5_l10,
	msm_mux_qup_se5_l11,
	msm_mux_qup_se5_l2,
	msm_mux_qup_se5_l3,
	msm_mux_qup_se5_l4,
	msm_mux_qup_se5_l5,
	msm_mux_qup_se6_l0,
	msm_mux_qup_se6_l1,
	msm_mux_qup_se6_l2,
	msm_mux_qup_se6_l3,
	msm_mux_qup_se7_l0,
	msm_mux_qup_se7_l1,
	msm_mux_qup_se7_l2,
	msm_mux_qup_se7_l3,
	msm_mux_resout,
	msm_mux_rx_los00,
	msm_mux_rx_los01,
	msm_mux_rx_los10,
	msm_mux_rx_los11,
	msm_mux_rx_los20,
	msm_mux_rx_los21,
	msm_mux_sdc_clk,
	msm_mux_sdc_cmd,
	msm_mux_sdc_data,
	msm_mux_tgu_ch0_trigout0,
	msm_mux_tgu_ch0_trigout1,
	msm_mux_tgu_ch0_trigout2,
	msm_mux_tgu_ch0_trigout3,
	msm_mux_tgu_ch1_trigout0,
	msm_mux_tgu_ch1_trigout1,
	msm_mux_tgu_ch1_trigout2,
	msm_mux_tgu_ch1_trigout3,
	msm_mux_tsens_max,
	msm_mux_NA,
};

#define MSM_PIN_FUNCTION(fname)				\
	[msm_mux_##fname] = {#fname, msm_mux_##fname}

static const struct pinctrl_function msm_pinctrl_functions[] = {
	MSM_PIN_FUNCTION(gpio),
	MSM_PIN_FUNCTION(Led00),
	MSM_PIN_FUNCTION(atest_char_start),
	MSM_PIN_FUNCTION(atest_char_status0),
	MSM_PIN_FUNCTION(atest_char_status1),
	MSM_PIN_FUNCTION(atest_char_status2),
	MSM_PIN_FUNCTION(atest_char_status3),
	MSM_PIN_FUNCTION(atest_tic_en),
	MSM_PIN_FUNCTION(audio_pri0),
	MSM_PIN_FUNCTION(audio_pri1),
	MSM_PIN_FUNCTION(audio_pri2),
	MSM_PIN_FUNCTION(audio_pri3),
	MSM_PIN_FUNCTION(audio_pri_d0),
	MSM_PIN_FUNCTION(audio_pri_d1),
	MSM_PIN_FUNCTION(audio_pri_fsync),
	MSM_PIN_FUNCTION(audio_pri_pclk),
	MSM_PIN_FUNCTION(audio_sec0),
	MSM_PIN_FUNCTION(audio_sec1),
	MSM_PIN_FUNCTION(audio_sec2),
	MSM_PIN_FUNCTION(audio_sec3),
	MSM_PIN_FUNCTION(audio_sec_d0),
	MSM_PIN_FUNCTION(audio_sec_d1),
	MSM_PIN_FUNCTION(audio_sec_fsync),
	MSM_PIN_FUNCTION(audio_sec_pclk),
	MSM_PIN_FUNCTION(bist_complete),
	MSM_PIN_FUNCTION(bist_fail),
	MSM_PIN_FUNCTION(bist_start),
	MSM_PIN_FUNCTION(bist_stop),
	MSM_PIN_FUNCTION(core_voltage_0),
	MSM_PIN_FUNCTION(core_voltage_1),
	MSM_PIN_FUNCTION(core_voltage_2),
	MSM_PIN_FUNCTION(core_voltage_3),
	MSM_PIN_FUNCTION(core_voltage_4),
	MSM_PIN_FUNCTION(core_voltage_5),
	MSM_PIN_FUNCTION(cri_trng0),
	MSM_PIN_FUNCTION(cri_trng1),
	MSM_PIN_FUNCTION(cri_trng2),
	MSM_PIN_FUNCTION(dbg_out_clk),
	MSM_PIN_FUNCTION(ddr_pxi00),
	MSM_PIN_FUNCTION(ddr_pxi01),
	MSM_PIN_FUNCTION(ddr_pxi10),
	MSM_PIN_FUNCTION(ddr_pxi11),
	MSM_PIN_FUNCTION(dg_out),
	MSM_PIN_FUNCTION(gcc_plltest_bypassnl),
	MSM_PIN_FUNCTION(gcc_plltest_resetn),
	MSM_PIN_FUNCTION(gcc_tlmm),
	MSM_PIN_FUNCTION(led01),
	MSM_PIN_FUNCTION(led02),
	MSM_PIN_FUNCTION(led10),
	MSM_PIN_FUNCTION(led11),
	MSM_PIN_FUNCTION(led12),
	MSM_PIN_FUNCTION(led20),
	MSM_PIN_FUNCTION(led21),
	MSM_PIN_FUNCTION(led22),
	MSM_PIN_FUNCTION(mdc_mst),
	MSM_PIN_FUNCTION(mdc_slv0),
	MSM_PIN_FUNCTION(mdc_slv1),
	MSM_PIN_FUNCTION(mdc_slv2),
	MSM_PIN_FUNCTION(mdio_mst),
	MSM_PIN_FUNCTION(mdio_slv),
	MSM_PIN_FUNCTION(mdio_slv0),
	MSM_PIN_FUNCTION(mdio_slv1),
	MSM_PIN_FUNCTION(mdio_slv2),
	MSM_PIN_FUNCTION(mux_tod_out),
	MSM_PIN_FUNCTION(pcie0_clk_req_n),
	MSM_PIN_FUNCTION(pcie0_wake),
	MSM_PIN_FUNCTION(pcie1_clk_req_n),
	MSM_PIN_FUNCTION(pcie1_wake),
	MSM_PIN_FUNCTION(pcie2_clk_req_n),
	MSM_PIN_FUNCTION(pcie2_wake),
	MSM_PIN_FUNCTION(pcie4_phy0),
	MSM_PIN_FUNCTION(pcie4_phy1),
	MSM_PIN_FUNCTION(pll_test),
	MSM_PIN_FUNCTION(pon_active_led),
	MSM_PIN_FUNCTION(pon_mux_sel),
	MSM_PIN_FUNCTION(pon_rx),
	MSM_PIN_FUNCTION(pon_rx_los),
	MSM_PIN_FUNCTION(pon_tx),
	MSM_PIN_FUNCTION(pon_tx_burst),
	MSM_PIN_FUNCTION(pon_tx_dis),
	MSM_PIN_FUNCTION(pon_tx_fault),
	MSM_PIN_FUNCTION(pon_tx_sd),
	MSM_PIN_FUNCTION(pps),
	MSM_PIN_FUNCTION(pwm_out00),
	MSM_PIN_FUNCTION(pwm_out01),
	MSM_PIN_FUNCTION(pwm_out02),
	MSM_PIN_FUNCTION(pwm_out03),
	MSM_PIN_FUNCTION(pwm_out10),
	MSM_PIN_FUNCTION(pwm_out11),
	MSM_PIN_FUNCTION(pwm_out12),
	MSM_PIN_FUNCTION(pwm_out13),
	MSM_PIN_FUNCTION(pwm_out20),
	MSM_PIN_FUNCTION(pwm_out21),
	MSM_PIN_FUNCTION(pwm_out22),
	MSM_PIN_FUNCTION(pwm_out23),
	MSM_PIN_FUNCTION(pwm_out30),
	MSM_PIN_FUNCTION(pwm_out31),
	MSM_PIN_FUNCTION(pwm_out32),
	MSM_PIN_FUNCTION(pwm_out33),
	MSM_PIN_FUNCTION(pwm_out40),
	MSM_PIN_FUNCTION(pwm_out41),
	MSM_PIN_FUNCTION(pwm_out42),
	MSM_PIN_FUNCTION(pwm_out43),
	MSM_PIN_FUNCTION(pwm_out50),
	MSM_PIN_FUNCTION(pwm_out51),
	MSM_PIN_FUNCTION(pwm_out52),
	MSM_PIN_FUNCTION(pwm_out53),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_a0),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_a1),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_b0),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_b1),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_a0),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_a1),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_b0),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_b1),
	MSM_PIN_FUNCTION(qdss_traceclk_a),
	MSM_PIN_FUNCTION(qdss_tracectl_a),
	MSM_PIN_FUNCTION(qdss_tracedata_a),
	MSM_PIN_FUNCTION(qspi_data),
	MSM_PIN_FUNCTION(qspi_clk),
	MSM_PIN_FUNCTION(qspi_cs),
	MSM_PIN_FUNCTION(qup_se0_l0),
	MSM_PIN_FUNCTION(qup_se0_l1),
	MSM_PIN_FUNCTION(qup_se0_l2),
	MSM_PIN_FUNCTION(qup_se0_l3),
	MSM_PIN_FUNCTION(qup_se0_l4),
	MSM_PIN_FUNCTION(qup_se0_l5),
	MSM_PIN_FUNCTION(qup_se1_l0),
	MSM_PIN_FUNCTION(qup_se1_l1),
	MSM_PIN_FUNCTION(qup_se1_l2),
	MSM_PIN_FUNCTION(qup_se1_l3),
	MSM_PIN_FUNCTION(qup_se2_l0),
	MSM_PIN_FUNCTION(qup_se2_l1),
	MSM_PIN_FUNCTION(qup_se2_l2),
	MSM_PIN_FUNCTION(qup_se2_l3),
	MSM_PIN_FUNCTION(qup_se3_l00),
	MSM_PIN_FUNCTION(qup_se3_l01),
	MSM_PIN_FUNCTION(qup_se3_l10),
	MSM_PIN_FUNCTION(qup_se3_l11),
	MSM_PIN_FUNCTION(qup_se3_l2),
	MSM_PIN_FUNCTION(qup_se3_l3),
	MSM_PIN_FUNCTION(qup_se4_l0),
	MSM_PIN_FUNCTION(qup_se4_l1),
	MSM_PIN_FUNCTION(qup_se4_l2),
	MSM_PIN_FUNCTION(qup_se4_l3),
	MSM_PIN_FUNCTION(qup_se4_l4),
	MSM_PIN_FUNCTION(qup_se4_l5),
	MSM_PIN_FUNCTION(qup_se5_l00),
	MSM_PIN_FUNCTION(qup_se5_l01),
	MSM_PIN_FUNCTION(qup_se5_l10),
	MSM_PIN_FUNCTION(qup_se5_l11),
	MSM_PIN_FUNCTION(qup_se5_l2),
	MSM_PIN_FUNCTION(qup_se5_l3),
	MSM_PIN_FUNCTION(qup_se5_l4),
	MSM_PIN_FUNCTION(qup_se5_l5),
	MSM_PIN_FUNCTION(qup_se6_l0),
	MSM_PIN_FUNCTION(qup_se6_l1),
	MSM_PIN_FUNCTION(qup_se6_l2),
	MSM_PIN_FUNCTION(qup_se6_l3),
	MSM_PIN_FUNCTION(qup_se7_l0),
	MSM_PIN_FUNCTION(qup_se7_l1),
	MSM_PIN_FUNCTION(qup_se7_l2),
	MSM_PIN_FUNCTION(qup_se7_l3),
	MSM_PIN_FUNCTION(resout),
	MSM_PIN_FUNCTION(rx_los00),
	MSM_PIN_FUNCTION(rx_los01),
	MSM_PIN_FUNCTION(rx_los10),
	MSM_PIN_FUNCTION(rx_los11),
	MSM_PIN_FUNCTION(rx_los20),
	MSM_PIN_FUNCTION(rx_los21),
	MSM_PIN_FUNCTION(sdc_clk),
	MSM_PIN_FUNCTION(sdc_cmd),
	MSM_PIN_FUNCTION(sdc_data),
	MSM_PIN_FUNCTION(tgu_ch0_trigout0),
	MSM_PIN_FUNCTION(tgu_ch0_trigout1),
	MSM_PIN_FUNCTION(tgu_ch0_trigout2),
	MSM_PIN_FUNCTION(tgu_ch0_trigout3),
	MSM_PIN_FUNCTION(tgu_ch1_trigout0),
	MSM_PIN_FUNCTION(tgu_ch1_trigout1),
	MSM_PIN_FUNCTION(tgu_ch1_trigout2),
	MSM_PIN_FUNCTION(tgu_ch1_trigout3),
	MSM_PIN_FUNCTION(tsens_max),

};

typedef unsigned int msm_pin_function[10];

#define PINGROUP(id, f1, f2, f3, f4, f5, f6, f7, f8, f9) \
	[id] = {        msm_mux_gpio, /* gpio mode */	\
			msm_mux_##f1,			\
			msm_mux_##f2,			\
			msm_mux_##f3,			\
			msm_mux_##f4,			\
			msm_mux_##f5,			\
			msm_mux_##f6,			\
			msm_mux_##f7,			\
			msm_mux_##f8,			\
			msm_mux_##f9,			\
	}

static const msm_pin_function ipq5610_pin_functions[] = {
	PINGROUP(0, sdc_data, qspi_data, pwm_out52, NA, NA, NA, NA, NA, NA),
	PINGROUP(1, sdc_data, qspi_data, pwm_out42, NA, NA, NA, NA, NA, NA),
	PINGROUP(2, sdc_data, qspi_data, pwm_out32, NA, NA, NA, NA, NA, NA),
	PINGROUP(3, sdc_data, qspi_data, pwm_out22, NA, NA, NA, NA, NA, NA),
	PINGROUP(4, sdc_cmd, qspi_cs, pwm_out12, NA, NA, NA, NA, NA, NA),
	PINGROUP(5, sdc_clk, qspi_clk, pwm_out02, NA, NA, NA, NA, NA, NA),
	PINGROUP(6, qup_se0_l2, led02, pwm_out31, NA, cri_trng0, qdss_tracedata_a, NA, NA, NA),
	PINGROUP(7, qup_se0_l3, led12, pwm_out21, NA, cri_trng1, qdss_tracedata_a, NA, NA, NA),
	PINGROUP(8, qup_se0_l0, pwm_out11, audio_pri2, audio_pri2, NA, cri_trng2, qdss_tracedata_a, NA, NA),
	PINGROUP(9, qup_se0_l1, led22, pwm_out01, NA, qdss_tracedata_a, NA, NA, NA, NA),
	PINGROUP(10, pon_rx_los, qup_se3_l3, pwm_out30, NA, NA, qdss_tracedata_a, NA, NA, NA),
	PINGROUP(11, pon_active_led, qup_se3_l2, pwm_out20, NA, NA, qdss_tracedata_a, NA, NA, NA),
	PINGROUP(12, pon_tx_dis, qup_se2_l3, pwm_out10, audio_pri0, audio_pri0, NA, qdss_tracedata_a, NA, NA),
	PINGROUP(13, NA, qup_se2_l2, pwm_out00, NA, NA, NA, NA, NA, NA),
	PINGROUP(14, pon_tx_burst, qup_se0_l4, pwm_out40, NA, qdss_tracedata_a, NA, NA, NA, NA),
	PINGROUP(15, pon_tx, qup_se0_l5, pwm_out50, NA, qdss_tracedata_a, NA, NA, NA, NA),
	PINGROUP(16, pon_tx_sd, audio_sec1, audio_sec1, NA, qdss_tracedata_a, tgu_ch1_trigout0, NA, NA, NA),
	PINGROUP(17, pon_tx_fault, audio_sec0, audio_sec0, NA, qdss_traceclk_a, tgu_ch1_trigout1, NA, NA, NA),
	PINGROUP(18, pps, pll_test, qdss_tracectl_a, tgu_ch1_trigout2, NA, NA, NA, NA, NA),
	PINGROUP(19, mux_tod_out, audio_pri1, audio_pri1, tgu_ch1_trigout3, NA, NA, NA, NA, NA),
	PINGROUP(20, qup_se2_l1, mdc_slv1, tsens_max, qdss_tracedata_a, pwm_out41, NA, NA, NA, NA),
	PINGROUP(21, qup_se2_l0, mdio_slv1, qdss_tracedata_a, pwm_out51, NA, NA, NA, NA, NA),
	PINGROUP(22, core_voltage_0, qup_se3_l10, pwm_out03, NA, NA, NA, NA, NA, NA),
	PINGROUP(23, Led00, dbg_out_clk, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(24, NA, NA, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(25, NA, NA, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(26, mdc_mst, pcie4_phy0, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(27, mdio_mst, pcie4_phy1, NA, qdss_cti_trig_out_b0, NA, NA, NA, NA, NA),
	PINGROUP(28, pcie1_clk_req_n, qup_se1_l1, NA, NA, qdss_cti_trig_out_a0, NA, NA, NA, NA),
	PINGROUP(29, NA, NA, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(30, pcie1_wake, qup_se1_l0, NA, NA, qdss_cti_trig_in_a0, NA, NA, NA, NA),
	PINGROUP(31, pcie0_clk_req_n, mdc_slv0, qup_se6_l3, NA, qdss_cti_trig_out_a1, NA, NA, NA, NA),
	PINGROUP(32, NA, NA, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(33, pcie0_wake, mdio_slv0, qdss_cti_trig_in_a1, qup_se6_l2, NA, NA, NA, NA, NA),
	PINGROUP(34, audio_pri_d0, atest_char_status0, qdss_cti_trig_in_b0, bist_start, ddr_pxi00, NA, NA, NA, NA),
	PINGROUP(35, audio_pri_d1, rx_los21, atest_char_status1, qdss_cti_trig_out_b1, bist_stop, ddr_pxi01, NA, NA, NA),
	PINGROUP(36, audio_pri_fsync, rx_los11, atest_char_status2, bist_complete, ddr_pxi00, NA, NA, NA, NA),
	PINGROUP(37, audio_pri_pclk, rx_los01, atest_char_status3, bist_fail, ddr_pxi01, NA, qdss_cti_trig_in_b1, NA, NA),
	PINGROUP(38, qup_se1_l3, led20, qdss_tracedata_a, NA, NA, NA, NA, NA, NA),
	PINGROUP(39, qup_se1_l2, led10, led01, gcc_tlmm, qdss_tracedata_a, NA, NA, NA, NA),
	PINGROUP(40, qup_se4_l2, rx_los20, audio_sec_fsync, qdss_tracedata_a, NA, NA, NA, NA, NA),
	PINGROUP(41, qup_se4_l3, rx_los10, audio_sec_pclk, mdio_slv, qdss_tracedata_a, NA, NA, NA, NA),
	PINGROUP(42, qup_se4_l0, rx_los00, audio_sec_d1, mdio_slv, atest_tic_en, NA, NA, NA, NA),
	PINGROUP(43, qup_se4_l1, audio_sec_d0, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(44, resout, NA, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(45, pon_mux_sel, ddr_pxi10, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(46, dg_out, atest_char_start, ddr_pxi11, NA, NA, NA, NA, NA, NA),
	PINGROUP(47, NA, mdc_slv2, qup_se5_l2, qup_se7_l3, audio_pri3, audio_pri3, NA, NA, NA),
	PINGROUP(48, pon_rx, qup_se5_l3, qup_se7_l2, tgu_ch0_trigout0, NA, NA, NA, NA, NA),
	PINGROUP(49, NA, mdio_slv2, qup_se5_l00, audio_sec2, audio_sec2, tgu_ch0_trigout1, NA, NA, NA),
	PINGROUP(50, NA, qup_se5_l10, audio_sec3, audio_sec3, tgu_ch0_trigout2, NA, NA, NA, NA),
	PINGROUP(51, NA, qup_se5_l4, tgu_ch0_trigout3, NA, NA, NA, NA, NA, NA),
	PINGROUP(52, qup_se7_l1, qup_se5_l5, qup_se4_l4, led21, NA, NA, NA, NA, NA),
	PINGROUP(53, qup_se7_l0, qup_se4_l5, led11, NA, NA, NA, NA, NA, NA),
	PINGROUP(54, pcie2_clk_req_n, NA, NA, qup_se5_l01, gcc_plltest_bypassnl, ddr_pxi10, NA, NA, NA),
	PINGROUP(55, NA, NA, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(56, pcie2_wake, qup_se5_l11, gcc_plltest_resetn, ddr_pxi11, NA, NA, NA, NA, NA),
	PINGROUP(57, core_voltage_1, qup_se3_l00, pwm_out13, NA, NA, NA, NA, NA, NA),
	PINGROUP(58, core_voltage_2, qup_se6_l0, pwm_out23, NA, NA, NA, NA, NA, NA),
	PINGROUP(59, core_voltage_3, qup_se6_l1, pwm_out33, NA, NA, NA, NA, NA, NA),
	PINGROUP(60, core_voltage_4, pwm_out43, NA, NA, qup_se3_l01, NA, NA, NA, NA),
	PINGROUP(61, core_voltage_5, pwm_out53, qup_se3_l11, NA, NA, NA, NA, NA, NA),
};

static const char *ipq5610_get_function_name(struct udevice *dev,
					     unsigned int selector)
{
	return msm_pinctrl_functions[selector].name;
}

static const char *ipq5610_get_pin_name(struct udevice *dev,
					unsigned int selector)
{
	snprintf(pin_name, MAX_PIN_NAME_LEN, "gpio%u", selector);
	return pin_name;
}

static unsigned int ipq5610_get_function_mux(unsigned int pin, unsigned int selector)
{
	unsigned int i;
	const msm_pin_function *func = ipq5610_pin_functions + pin;

	for (i = 0; i < 10; i++)
		if ((*func)[i] == selector)
			return i;

	pr_err("Can't find requested function for pin %u pin\n", pin);
	return -EINVAL;
}

static const struct msm_pinctrl_data ipq5610_data = {
	.pin_data = {
		.pin_count = 62,
	},
	.functions_count = ARRAY_SIZE(msm_pinctrl_functions),
	.get_function_name = ipq5610_get_function_name,
	.get_function_mux = ipq5610_get_function_mux,
	.get_pin_name = ipq5610_get_pin_name,
};

static const struct udevice_id msm_pinctrl_ids[] = {
	{ .compatible = "qcom,ipq5610-tlmm", .data = (ulong)&ipq5610_data },
	{ /* Sentinal */ }
};

U_BOOT_DRIVER(pinctrl_ipq5610) = {
	.name		= "pinctrl_ipq5610",
	.id		= UCLASS_NOP,
	.of_match	= msm_pinctrl_ids,
	.ops		= &msm_pinctrl_ops,
	.bind		= msm_pinctrl_bind,
	.flags = DM_FLAG_PRE_RELOC,
};
