// SPDX-License-Identifier: GPL-2.0+
/*
 * Qualcomm IPQ5210 pinctrl
 *
 * Copyright (c) 2019 Sartura Ltd.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * Author: Robert Marko <robert.marko@sartura.hr>
 */

#include <dm.h>

#include "pinctrl-qcom.h"

#define MAX_PIN_NAME_LEN 32
static char pin_name[MAX_PIN_NAME_LEN] __section(".data");

enum ipq5210_functions {
	msm_mux_gpio,
	msm_mux_sdc_data,
	msm_mux_qspi_data,
	msm_mux_pwm_out0,
	msm_mux_pwm_out1,
	msm_mux_pwm_out2,
	msm_mux_pwm_out3,
	msm_mux_dbg_bus_out,
	msm_mux_spare,
	msm_mux_tm_clk,
	msm_mux_tm_ack,
	msm_mux_tm_req_a,
	msm_mux_tm_req_b,
	msm_mux_sdc_cmd,
	msm_mux_qspi_cs,
	msm_mux_qspi_clk,
	msm_mux_sdc_clk,
	msm_mux_qup_se0_l2,
	msm_mux_qup_se0_l3,
	msm_mux_qup_se0_l0,
	msm_mux_qup_se0_l1,
	msm_mux_led0,
	msm_mux_led1,
	msm_mux_led2,
	msm_mux_audio_pri_mclk_out,
	msm_mux_audio_pri_mclk_in,
	msm_mux_cri_trng_rosc_test_out,
	msm_mux_qdss_tracedata_a,
	msm_mux_boot_config,
	msm_mux_qup_se3_l3,
	msm_mux_gp0_clk,
	msm_mux_qup_se3_l2,
	msm_mux_gp1_clk,
	msm_mux_sdc_cdc_dtest_out,
	msm_mux_qrng_rosc_test_out,
	msm_mux_pon_rx_los,
	msm_mux_pon_active_led,
	msm_mux_pon_tx_dis,
	msm_mux_gpn_tx_dis,
	msm_mux_pon_tx_burst,
	msm_mux_pon_tx_pwr_on,
	msm_mux_pon_tx_sd,
	msm_mux_pon_tx_fault,
	msm_mux_audio_sec_mclk_out,
	msm_mux_audio_sec_mclk_in,
	msm_mux_qdss_cti_trig_out_b0,
	msm_mux_pps,
	msm_mux_pll_test,
	msm_mux_mux_tod_out,
	msm_mux_mdc_slv,
	msm_mux_tsens_max_temp_pwm,
	msm_mux_mdio_slv,
	msm_mux_core_voltage_0,
	msm_mux_qup_se3_l1,
	msm_mux_qup_se3_l0,
	msm_mux_dbg_out_clk,
	msm_mux_qdss_traceclk_a,
	msm_mux_tm_bus,
	msm_mux_mdc_mst,
	msm_mux_qdss_tracectl_a,
	msm_mux_mdio_mst,
	msm_mux_qup_se1_l1,
	msm_mux_qup_se1_l0,
	msm_mux_pcie1_clk_req_n,
	msm_mux_pcie1_wake,
	msm_mux_pcie0_clk_req_n,
	msm_mux_pcie0_wake,
	msm_mux_qup_se1_l3,
	msm_mux_gcc_plltest_bypassnl,
	msm_mux_qup_se1_l2,
	msm_mux_gcc_tlmm_pll_lock_det_out,
	msm_mux_audio_pri_d0,
	msm_mux_atest_char_status,
	msm_mux_qdss_cti_trig_in_b0,
	msm_mux_eud_gpio_tms,
	msm_mux_audio_pri_d1,
	msm_mux_rx_los2,
	msm_mux_qdss_cti_trig_out_b1,
	msm_mux_eud_gpio_tdo,
	msm_mux_audio_pri_fsync,
	msm_mux_rx_los1,
	msm_mux_eud_gpio_tck,
	msm_mux_audio_pri_pclk,
	msm_mux_rx_los0,
	msm_mux_qdss_cti_trig_in_b1,
	msm_mux_eud_gpio_tdi,
	msm_mux_qup_se4_l2,
	msm_mux_audio_sec_fsync,
	msm_mux_gcc_plltest_resetn,
	msm_mux_qup_se4_l3,
	msm_mux_audio_sec_pclk,
	msm_mux_qup_se4_l0,
	msm_mux_audio_sec_d1,
	msm_mux_atest_tic_en,
	msm_mux_eud_gpio_srst_n,
	msm_mux_qup_se4_l1,
	msm_mux_audio_sec_d0,
	msm_mux_resout,
	msm_mux_pon_mux_sel,
	msm_mux_forced_usb_boot,
	msm_mux_dg_out,
	msm_mux_atest_char_start,
	msm_mux_atest_sub_mode_0,
	msm_mux_qup_se5_l2,
	msm_mux_atest_usb0_atereset,
	msm_mux_qup_se5_l3,
	msm_mux_atest_usb0_atestdataout,
	msm_mux_qup_se5_l0,
	msm_mux_qup_se5_l1,
	msm_mux_qup_se5_l4,
	msm_mux_qup_se5_l5,
	msm_mux_qdss_cti_trig_out_a0,
	msm_mux_qdss_cti_trig_in_a0,
	msm_mux_qdss_cti_trig_out_a1,
	msm_mux_qdss_cti_trig_in_a1,
	msm_mux_eud_gpio_trst_n,
	msm_mux_qup_se4_l4,
	msm_mux_qup_se4_l5,
	msm_mux_qup_se2_l0,
	msm_mux_qup_se2_l1,
	msm_mux_qup_se2_l2,
	msm_mux_qup_se2_l3,
	msm_mux_qup_se0_l4,
	msm_mux_qup_se0_l5,
	msm_mux_gpn_rx_los,
	msm_mux_pon_rx_pwr_on,
	msm_mux_gpn_tx_fault,
	msm_mux_gpn_tx_sd,
	msm_mux_gpn_tx_burst,
	msm_mux_NA,
};

#define MSM_PIN_FUNCTION(fname)				\
	[msm_mux_##fname] = {#fname, msm_mux_##fname}

static const struct pinctrl_function msm_pinctrl_functions[] = {
	MSM_PIN_FUNCTION(gpio),
	MSM_PIN_FUNCTION(sdc_data),
	MSM_PIN_FUNCTION(qspi_data),
	MSM_PIN_FUNCTION(pwm_out0),
	MSM_PIN_FUNCTION(pwm_out1),
	MSM_PIN_FUNCTION(pwm_out2),
	MSM_PIN_FUNCTION(pwm_out3),
	MSM_PIN_FUNCTION(dbg_bus_out),
	MSM_PIN_FUNCTION(spare),
	MSM_PIN_FUNCTION(tm_clk),
	MSM_PIN_FUNCTION(tm_ack),
	MSM_PIN_FUNCTION(tm_req_a),
	MSM_PIN_FUNCTION(tm_req_b),
	MSM_PIN_FUNCTION(sdc_cmd),
	MSM_PIN_FUNCTION(qspi_cs),
	MSM_PIN_FUNCTION(qspi_clk),
	MSM_PIN_FUNCTION(sdc_clk),
	MSM_PIN_FUNCTION(qup_se0_l2),
	MSM_PIN_FUNCTION(qup_se0_l3),
	MSM_PIN_FUNCTION(qup_se0_l0),
	MSM_PIN_FUNCTION(qup_se0_l1),
	MSM_PIN_FUNCTION(led0),
	MSM_PIN_FUNCTION(led1),
	MSM_PIN_FUNCTION(led2),
	MSM_PIN_FUNCTION(audio_pri_mclk_out),
	MSM_PIN_FUNCTION(audio_pri_mclk_in),
	MSM_PIN_FUNCTION(cri_trng_rosc_test_out),
	MSM_PIN_FUNCTION(qdss_tracedata_a),
	MSM_PIN_FUNCTION(boot_config),
	MSM_PIN_FUNCTION(qup_se3_l3),
	MSM_PIN_FUNCTION(gp0_clk),
	MSM_PIN_FUNCTION(qup_se3_l2),
	MSM_PIN_FUNCTION(gp1_clk),
	MSM_PIN_FUNCTION(sdc_cdc_dtest_out),
	MSM_PIN_FUNCTION(qrng_rosc_test_out),
	MSM_PIN_FUNCTION(pon_rx_los),
	MSM_PIN_FUNCTION(pon_active_led),
	MSM_PIN_FUNCTION(pon_tx_dis),
	MSM_PIN_FUNCTION(gpn_tx_dis),
	MSM_PIN_FUNCTION(pon_tx_burst),
	MSM_PIN_FUNCTION(pon_tx_pwr_on),
	MSM_PIN_FUNCTION(pon_tx_sd),
	MSM_PIN_FUNCTION(pon_tx_fault),
	MSM_PIN_FUNCTION(audio_sec_mclk_out),
	MSM_PIN_FUNCTION(audio_sec_mclk_in),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_b0),
	MSM_PIN_FUNCTION(pps),
	MSM_PIN_FUNCTION(pll_test),
	MSM_PIN_FUNCTION(mux_tod_out),
	MSM_PIN_FUNCTION(mdc_slv),
	MSM_PIN_FUNCTION(tsens_max_temp_pwm),
	MSM_PIN_FUNCTION(mdio_slv),
	MSM_PIN_FUNCTION(core_voltage_0),
	MSM_PIN_FUNCTION(qup_se3_l1),
	MSM_PIN_FUNCTION(qup_se3_l0),
	MSM_PIN_FUNCTION(dbg_out_clk),
	MSM_PIN_FUNCTION(qdss_traceclk_a),
	MSM_PIN_FUNCTION(tm_bus),
	MSM_PIN_FUNCTION(mdc_mst),
	MSM_PIN_FUNCTION(qdss_tracectl_a),
	MSM_PIN_FUNCTION(mdio_mst),
	MSM_PIN_FUNCTION(qup_se1_l1),
	MSM_PIN_FUNCTION(qup_se1_l0),
	MSM_PIN_FUNCTION(pcie1_clk_req_n),
	MSM_PIN_FUNCTION(pcie1_wake),
	MSM_PIN_FUNCTION(pcie0_clk_req_n),
	MSM_PIN_FUNCTION(pcie0_wake),
	MSM_PIN_FUNCTION(qup_se1_l3),
	MSM_PIN_FUNCTION(gcc_plltest_bypassnl),
	MSM_PIN_FUNCTION(qup_se1_l2),
	MSM_PIN_FUNCTION(gcc_tlmm_pll_lock_det_out),
	MSM_PIN_FUNCTION(audio_pri_d0),
	MSM_PIN_FUNCTION(atest_char_status),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_b0),
	MSM_PIN_FUNCTION(eud_gpio_tms),
	MSM_PIN_FUNCTION(audio_pri_d1),
	MSM_PIN_FUNCTION(rx_los2),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_b1),
	MSM_PIN_FUNCTION(eud_gpio_tdo),
	MSM_PIN_FUNCTION(audio_pri_fsync),
	MSM_PIN_FUNCTION(rx_los1),
	MSM_PIN_FUNCTION(eud_gpio_tck),
	MSM_PIN_FUNCTION(audio_pri_pclk),
	MSM_PIN_FUNCTION(rx_los0),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_b1),
	MSM_PIN_FUNCTION(eud_gpio_tdi),
	MSM_PIN_FUNCTION(qup_se4_l2),
	MSM_PIN_FUNCTION(audio_sec_fsync),
	MSM_PIN_FUNCTION(gcc_plltest_resetn),
	MSM_PIN_FUNCTION(qup_se4_l3),
	MSM_PIN_FUNCTION(audio_sec_pclk),
	MSM_PIN_FUNCTION(qup_se4_l0),
	MSM_PIN_FUNCTION(audio_sec_d1),
	MSM_PIN_FUNCTION(atest_tic_en),
	MSM_PIN_FUNCTION(eud_gpio_srst_n),
	MSM_PIN_FUNCTION(qup_se4_l1),
	MSM_PIN_FUNCTION(audio_sec_d0),
	MSM_PIN_FUNCTION(resout),
	MSM_PIN_FUNCTION(pon_mux_sel),
	MSM_PIN_FUNCTION(forced_usb_boot),
	MSM_PIN_FUNCTION(dg_out),
	MSM_PIN_FUNCTION(atest_char_start),
	MSM_PIN_FUNCTION(atest_sub_mode_0),
	MSM_PIN_FUNCTION(qup_se5_l2),
	MSM_PIN_FUNCTION(atest_usb0_atereset),
	MSM_PIN_FUNCTION(qup_se5_l3),
	MSM_PIN_FUNCTION(atest_usb0_atestdataout),
	MSM_PIN_FUNCTION(qup_se5_l0),
	MSM_PIN_FUNCTION(qup_se5_l1),
	MSM_PIN_FUNCTION(qup_se5_l4),
	MSM_PIN_FUNCTION(qup_se5_l5),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_a0),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_a0),
	MSM_PIN_FUNCTION(qdss_cti_trig_out_a1),
	MSM_PIN_FUNCTION(qdss_cti_trig_in_a1),
	MSM_PIN_FUNCTION(eud_gpio_trst_n),
	MSM_PIN_FUNCTION(qup_se4_l4),
	MSM_PIN_FUNCTION(qup_se4_l5),
	MSM_PIN_FUNCTION(qup_se2_l0),
	MSM_PIN_FUNCTION(qup_se2_l1),
	MSM_PIN_FUNCTION(qup_se2_l2),
	MSM_PIN_FUNCTION(qup_se2_l3),
	MSM_PIN_FUNCTION(qup_se0_l4),
	MSM_PIN_FUNCTION(qup_se0_l5),
	MSM_PIN_FUNCTION(gpn_rx_los),
	MSM_PIN_FUNCTION(pon_rx_pwr_on),
	MSM_PIN_FUNCTION(gpn_tx_fault),
	MSM_PIN_FUNCTION(gpn_tx_sd),
	MSM_PIN_FUNCTION(gpn_tx_burst),
};

typedef unsigned int msm_pin_function[10];

#define PINGROUP(id, f1, f2, f3, f4, f5, f6, f7, f8, f9) \
	[id] = {        msm_mux_gpio, \
			msm_mux_##f1, \
			msm_mux_##f2, \
			msm_mux_##f3, \
			msm_mux_##f4, \
			msm_mux_##f5, \
			msm_mux_##f6, \
			msm_mux_##f7, \
			msm_mux_##f8, \
			msm_mux_##f9, \
	}

static const msm_pin_function ipq5210_pin_functions[] = {
	PINGROUP(0, sdc_data, qspi_data, pwm_out3, dbg_bus_out, spare, tm_clk, NA, NA, NA),
	PINGROUP(1, sdc_data, qspi_data, pwm_out2, dbg_bus_out, spare, tm_ack, NA, NA, NA),
	PINGROUP(2, sdc_data, qspi_data, pwm_out1, dbg_bus_out, spare, tm_req_a, NA, NA, NA),
	PINGROUP(3, sdc_data, qspi_data, pwm_out0, dbg_bus_out, spare, tm_req_b, NA, NA, NA),
	PINGROUP(4, sdc_cmd, qspi_cs, dbg_bus_out, spare, tm_bus, NA, NA, NA, NA),
	PINGROUP(5, sdc_clk, qspi_clk, dbg_bus_out, spare, tm_bus, NA, NA, NA, NA),
	PINGROUP(6, qup_se0_l2, led0, pwm_out3, dbg_bus_out, cri_trng_rosc_test_out, qdss_tracedata_a, spare, boot_config, tm_bus),
	PINGROUP(7, qup_se0_l3, led1, pwm_out2, dbg_bus_out, cri_trng_rosc_test_out, qdss_tracedata_a, spare, tm_bus, NA),
	PINGROUP(8, qup_se0_l0, pwm_out1, audio_pri_mclk_out, audio_pri_mclk_in, dbg_bus_out, cri_trng_rosc_test_out, qdss_tracedata_a, spare, tm_bus),
	PINGROUP(9, qup_se0_l1, led2, pwm_out0, dbg_bus_out, cri_trng_rosc_test_out, qdss_tracedata_a, spare, boot_config, tm_bus),
	PINGROUP(10, pon_rx_los, qup_se3_l3, pwm_out3, gp0_clk, dbg_bus_out, qdss_tracedata_a, sdc_cdc_dtest_out, spare, tm_bus),
	PINGROUP(11, pon_active_led, qup_se3_l2, pwm_out2, gp1_clk, dbg_bus_out, qdss_tracedata_a, sdc_cdc_dtest_out, spare, boot_config),
	PINGROUP(12, pon_tx_dis, qup_se2_l3, pwm_out1, audio_pri_mclk_out, audio_pri_mclk_in, dbg_bus_out, qrng_rosc_test_out, qdss_tracedata_a, spare),
	PINGROUP(13, gpn_tx_dis, qup_se2_l2, pwm_out0, audio_pri_mclk_out, audio_pri_mclk_in, dbg_bus_out, qrng_rosc_test_out, qdss_tracedata_a, spare),
	PINGROUP(14, pon_tx_burst, qup_se0_l4, dbg_bus_out, qrng_rosc_test_out, qdss_tracedata_a, spare, tm_bus, NA, NA),
	PINGROUP(15, pon_tx_pwr_on, qup_se0_l5, dbg_bus_out, qdss_tracedata_a, spare, tm_bus, NA, NA, NA),
	PINGROUP(16, pon_tx_sd, audio_sec_mclk_out, audio_sec_mclk_in, qdss_cti_trig_out_b0, dbg_bus_out, spare, tm_bus, NA, NA),
	PINGROUP(17, pon_tx_fault, audio_sec_mclk_out, audio_sec_mclk_in, dbg_bus_out, spare, tm_bus, NA, NA, NA),
	PINGROUP(18, pps, pll_test, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(19, mux_tod_out, audio_pri_mclk_out, audio_pri_mclk_in, spare, NA, NA, NA, NA, NA),
	PINGROUP(20, qup_se2_l1, mdc_slv, tsens_max_temp_pwm, qdss_tracedata_a, dbg_bus_out, spare, tm_bus, NA, NA),
	PINGROUP(21, qup_se2_l0, mdio_slv, qdss_tracedata_a, dbg_bus_out, spare, tm_bus, NA, NA, NA),
	PINGROUP(22, core_voltage_0, qup_se3_l1, pwm_out0, spare, NA, NA, NA, NA, NA),
	PINGROUP(23, led0, qup_se3_l0, dbg_out_clk, qdss_traceclk_a, spare, NA, NA, NA, NA),
	PINGROUP(24, spare, tm_bus, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(25, spare, tm_bus, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(26, mdc_mst, led2, dbg_bus_out, qdss_tracectl_a, spare, boot_config, tm_bus, NA, NA),
	PINGROUP(27, mdio_mst, led1, dbg_bus_out, spare, tm_bus, NA, NA, NA, NA),
	PINGROUP(28, pcie1_clk_req_n, qup_se1_l1, gp0_clk, dbg_bus_out, qdss_cti_trig_out_a0, spare, tm_bus, NA, NA),
	PINGROUP(29, dbg_bus_out, spare, boot_config, tm_bus, NA, NA, NA, NA, NA),
	PINGROUP(30, pcie1_wake, qup_se1_l0, gp1_clk, dbg_bus_out, qdss_cti_trig_in_a0, spare, tm_bus, NA, NA),
	PINGROUP(31, pcie0_clk_req_n, mdc_slv, dbg_bus_out, qdss_cti_trig_out_a1, spare, tm_bus, NA, NA, NA),
	PINGROUP(32, dbg_bus_out, spare, tm_bus, NA, NA, NA, NA, NA, NA),
	PINGROUP(33, pcie0_wake, mdio_slv, qdss_cti_trig_in_a1, dbg_bus_out, spare, tm_bus, NA, NA, NA),
	PINGROUP(34, audio_pri_d0, atest_char_status, qdss_cti_trig_in_b0, dbg_bus_out, spare, eud_gpio_tms, NA, NA, NA),
	PINGROUP(35, audio_pri_d1, rx_los2, atest_char_status, qdss_cti_trig_out_b1, dbg_bus_out, spare, eud_gpio_tdo, NA, NA),
	PINGROUP(36, audio_pri_fsync, spare, rx_los1, atest_char_status, dbg_bus_out, spare, eud_gpio_tck, NA, NA),
	PINGROUP(37, audio_pri_pclk, rx_los0, atest_char_status, dbg_bus_out, qdss_cti_trig_in_b1, spare, eud_gpio_tdi, NA, NA),
	PINGROUP(38, qup_se1_l3, led2, gcc_plltest_bypassnl, qdss_tracedata_a, spare, tm_bus, NA, NA, NA),
	PINGROUP(39, qup_se1_l2, led1, led0, gcc_tlmm_pll_lock_det_out, qdss_tracedata_a, spare, boot_config, NA, NA),
	PINGROUP(40, qup_se4_l2, rx_los2, audio_sec_fsync, gcc_plltest_resetn, qdss_tracedata_a, spare, tm_bus, NA, NA),
	PINGROUP(41, qup_se4_l3, rx_los1, audio_sec_pclk, qdss_tracedata_a, spare, eud_gpio_trst_n, atest_sub_mode_0, NA, NA),
	PINGROUP(42, qup_se4_l0, rx_los0, audio_sec_d1, atest_tic_en, spare, eud_gpio_srst_n, NA, NA, NA),
	PINGROUP(43, qup_se4_l1, audio_sec_d0, spare, boot_config, tm_bus, NA, NA, NA, NA),
	PINGROUP(44, resout, spare, NA, NA, NA, NA, NA, NA, NA),
	PINGROUP(45, pon_mux_sel, spare, forced_usb_boot, tm_bus, NA, NA, NA, NA, NA),
	PINGROUP(46, dg_out, atest_char_start, spare, atest_sub_mode_0, NA, NA, NA, NA, NA),
	PINGROUP(47, gpn_rx_los, mdc_slv, qup_se5_l2, spare, atest_usb0_atereset, NA, NA, NA, NA),
	PINGROUP(48, pon_rx_pwr_on, qup_se5_l3, spare, atest_usb0_atestdataout, NA, NA, NA, NA, NA),
	PINGROUP(49, gpn_tx_fault, mdio_slv, qup_se5_l0, audio_sec_mclk_out, audio_sec_mclk_in, spare, atest_usb0_atestdataout, NA, NA),
	PINGROUP(50, gpn_tx_sd, qup_se5_l1, audio_sec_mclk_out, audio_sec_mclk_in, spare, atest_usb0_atestdataout, NA, NA, NA),
	PINGROUP(51, gpn_tx_burst, qup_se5_l4, spare, atest_usb0_atestdataout, NA, NA, NA, NA, NA),
	PINGROUP(52, qup_se2_l1, qup_se5_l5, qup_se4_l4, qup_se5_l0, spare, tm_bus, NA, NA, NA),
	PINGROUP(53, qup_se2_l0, qup_se4_l5, qup_se5_l1, spare, tm_bus, NA, NA, NA, NA),
};

static const char *ipq5210_get_function_name(struct udevice *dev,
					     unsigned int selector)
{
	return msm_pinctrl_functions[selector].name;
}

static const char *ipq5210_get_pin_name(struct udevice *dev,
					unsigned int selector)
{
	snprintf(pin_name, MAX_PIN_NAME_LEN, "gpio%u", selector);
	return pin_name;
}

static unsigned int ipq5210_get_function_mux(unsigned int pin,
					     unsigned int selector)
{
	unsigned int i;
	const msm_pin_function *func = ipq5210_pin_functions + pin;

	for (i = 0; i < 10; i++)
		if ((*func)[i] == selector)
			return i;

	pr_err("Can't find requested function for pin %u pin\n", pin);
	return -EINVAL;
}

static const struct msm_pinctrl_data ipq5210_data = {
	.pin_data = {
		.pin_count = 54,
		.special_pins_start = 54,
	},
	.functions_count = ARRAY_SIZE(msm_pinctrl_functions),
	.get_function_name = ipq5210_get_function_name,
	.get_function_mux = ipq5210_get_function_mux,
	.get_pin_name = ipq5210_get_pin_name,
};

static const struct udevice_id msm_pinctrl_ids[] = {
	{ .compatible = "qcom,ipq5210-tlmm", .data = (ulong)&ipq5210_data },
	{ }
};

U_BOOT_DRIVER(pinctrl_ipq5210) = {
	.name		= "pinctrl_ipq5210",
	.id		= UCLASS_NOP,
	.of_match	= msm_pinctrl_ids,
	.ops		= &msm_pinctrl_ops,
	.bind		= msm_pinctrl_bind,
	.flags = DM_FLAG_PRE_RELOC,
};
