# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries. 
#
# QTI SoftSKU Utilities - License Store Library

obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += Crc32.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += DataMgrStorage.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += DataStoreMgr.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += LicenseStore.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += MDTable.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += UsefulBuf.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += Utils.o
obj-$(CONFIG_IPQ_SOFTSKU_SUPPORT) += VarDataStoreError.o

ccflags-y += -I$(srctree)/arch/arm/mach-ipq/qti_softsku_utils/include
